### ISSUE TITLE
Rikaisuru, Rikaisuru

### ISSUE THREAD

**Issue by chuigda** [Zhihang-Liu/Cement#1]
你又开始了

**Comment by imlyzh** [comment]
我又开始了

**Comment by chuigda** [comment]
Why not moving this repository to malt-lang organization?

**Comment by imlyzh** [comment]
因为malt-lang是我的黑历史，而我现在要洗刷掉我的黑历史。
至于我为什么不删了malt-lang，我想留在那，让Github帮我记着它

**Comment by imlyzh** [comment]
如果有一天，我经过cement这个过度，把Malt3实现出来了，那我可能会把Malt3移到malt-lang里
